version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    image: ghcr.io/cfc-servers/cfc_iris:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -t 5:5 -p 3115"
    volumes:
      - .:/iris-backend
    ports:
      - "3115:3115"
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=dummy
    depends_on:
      - db
