version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    image: ghcr.io/cfc-servers/cfc_iris:latest
    command: puma -t 5:5 -p 3115
    volumes:
      - .:/app:cached
      - content:/app/public/frontend
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=dummy
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - content:/usr/share/nginx/html
    ports:
      - "3115:80"
    depends_on:
      - web

volumes:
  content: {}
