# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf-8
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: iris_development

test:
  <<: *default
  database: iris_test

production:
  <<: *default
  database: iris_prod
